namespace: ecommerce-2

frontend:
  deploymentname: frontend-service #User for labels
  servicename: frontend-service
  replicaCount: 1
  image:
    repository: abhishek661/frontend
    tag: v3
  port: 5000

user:
  deploymentname: user-service #user for labels
  servicename: user-service
  replicaCount: 1
  image:
    repository: abhishek661/user
    tag: v2
  port: 5001

product:
  deploymentname: product-service #user for labels 
  servicename: product-service
  replicaCount: 1
  image:
    repository: abhishek661/product
    tag: v2
  port: 5002

order:
  deploymentname: order-service # user for labels
  servicename: order-service
  replicaCount: 1
  image:
    repository: abhishek661/order
    tag: v2
  port: 5003

mongo:
  deploymentname: mongo
  pvcname: mongo # user for labels
  servicename: mongo-service
  pvc-name: mongo
  replicaCount: 1
  image:
    repository: mongo
    tag: "7"
  port: 27017

  storage:
    size: 1Gi
    storageClass: gp2

config:
  configname: ecommerce-config
  mongoUri: "mongodb://mongo-service:27017/"

  frontend:
    userServiceUrl: "/api/users"
    productServiceUrl: "/api/products"
    orderServiceUrl: "/api/orders"

  order:
    userServiceUrl: "http://user-service:5001"
    productServiceUrl: "http://product-service:5002"

secret:
  secretname: ecommerce-secret
  secretKey: "ecommerce-super-secret"

service:
  type: NodePort

ingress:
  name: ecommerce-ingress
  enabled: true
  ingressClassName: nginx
  scheme: internet-facing
  targetType: instance