apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: ecommerce-2
data:
  MONGO_URI: "mongodb://mongo-service:27017/"
  USER_SERVICE_URL: "http://a1bb43141f3ce4d6c930baab4834177a-cebd04b3184c1769.elb.us-east-1.amazonaws.com/api/users"
  PRODUCT_SERVICE_URL: "http://a1bb43141f3ce4d6c930baab4834177a-cebd04b3184c1769.elb.us-east-1.amazonaws.com/api/products"
  ORDER_SERVICE_URL: "http://a1bb43141f3ce4d6c930baab4834177a-cebd04b3184c1769.elb.us-east-1.amazonaws.com/api/orders"
