apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service-name }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}

  selector:
    app: {{ .Values.frontend.deployment-name }}

  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}