apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.deploymentname }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  strategy:
    type: {{ .Values.strategy.type }}
    rollingUpdate:
      maxUnavailable: {{ .Values.strategy.maxUnavailable }}
      maxSurge: {{ .Values/strategy.maxSurge }}

  selector:
    matchLabels:
      app: {{ .Values.frontend.deploymentname }}

  template:
    metadata:
      labels:
        app: {{ .Values.frontend.deploymentname }}

    spec:
      containers:
        - name: frontend-service

          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"

          ports:
            - containerPort: {{ .Values.frontend.port }}

          env:
            - name: USER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config
                  key: FRONTEND_USER_SERVICE_URL

            - name: PRODUCT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config
                  key: FRONTEND_PRODUCT_SERVICE_URL

            - name: ORDER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config
                  key: FRONTEND_ORDER_SERVICE_URL