{{- if .Values.ingress.enabled }}

apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: {{ .Values.ingress.name }}
  namespace: {{ .Values.namespace }}

  annotations:
    alb.ingress.kubernetes.io/scheme: {{ .Values.ingress.scheme }}
    alb.ingress.kubernetes.io/target-type: {{ .Values.ingress.targetType }}
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/success-codes: "200"

spec:

  ingressClassName: {{ .Values.ingress.ingressClassName }}

  rules:
    - http:

        paths:

          - path: /api/users
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.user.servicename }}
                port:
                  number: {{ .Values.user.port }}

          - path: /api/products
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.product.servicename }}
                port:
                  number: {{ .Values.product.port }}

          - path: /api/orders
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.order.servicename }}
                port:
                  number: {{ .Values.order.port }}

          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.frontend.servicename }}
                port:
                  number: {{ .Values.frontend.port }}

{{- end }}