apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongo.servicename }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}

  selector:
    app: {{ .Values.mongo.deploymentname }}

  ports:
    - port: {{ .Values.mongo.port }}
      targetPort: {{ .Values.mongo.port }}