apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mongo.deployment-name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.mongo.replicaCount }}

  selector:
    matchLabels:
      app: {{ .Values.mongo.deployment-name }}

  template:
    metadata:
      labels:
        app: {{ .Values.mongo.deployment-name }}

    spec:
      containers:
        - name: mongo

          image: "{{ .Values.mongo.image.repository }}:{{ .Values.mongo.image.tag }}"

          ports:
            - containerPort: {{ .Values.mongo.port }}

          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db

      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-pvc