apiVersion: v1
kind: Service
metadata:
  name:  {{ .Values.order.service-name }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}

  selector:
    app:  {{ .Values.order.deployment-name }}

  ports:
    - port: {{ .Values.order.port }}
      targetPort: {{ .Values.order.port }}